[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }      # Futures crate for working with asynchronous streams
futures = "0.3" 
